[package]
name = "zeroshade"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.12.2"

[dependencies]
starknet = ">=2.12.0, <3.0.0"
# OpenZeppelin ya no es necesario - PausableERC20 ahora es un Token simple
# openzeppelin = { path = "../cairo-contracts" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.18.0" }

